version: '3'
services:
  database:
    image: postgres:9.6-stretch
    environment:
      POSTGRES_PASSWORD: abacate
  
  web:
    build: .
    ports:
      - "8081:8081"
    depends_on: 
      - database
    links:
      - database
  