version: '3'
services:
  database:
    image: postgres:9.6-stretch
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - "5032:5032"
    volumes:
      - .:/app/postgressql
    
  web:
    build: .
    command: "go run ./cmd/api"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    links:
      - database
