version: '3'
services:
  tradulab-db:
    image: postgres:9.6-stretch
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: tradulab
    ports: 
      - "5432:5432"
    networks:
      tradulab-network: {}
    
  web:
    build: .
    command: "go run ./cmd/api"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - tradulab-db
    networks:
      tradulab-network: {}
    env_file:
      - .env

    
  migrate:
    build: .
    command: "go run ./cmd/migrate"
    volumes:
      - .:/app
    depends_on:
      - tradulab-db
    networks:
      tradulab-network: {}

networks:
  tradulab-network:
    name: tradulab-network
    external: false
