version: '3'
services:
  app:
    container_name: tradulab-service
    build: .
    ports: 8081:8081
    depends_on: 
      - db-postgres
      
  db-postgres:
    image: postgres:9.6-stretch
    environment:
    POSTGRES_PASSWORD: abacate