version: '3'
services:
  database:
    image: postgres:9.6-stretch
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: tradulab
    ports: 
      - "5032:5432"
    
  web:
    build: .
    command: "go run ./cmd/api"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    links:
      - database
    
  migrate:
    build: .
    command: "go run ./cmd/migrate"
    volumes:
      - .:/app
    links:
      - database
